services:
  mc:
    image: itzg/minecraft-server:java25
    container_name: mc
    tty: true
    stdin_open: true
    ports:
      - "${MC_PORT}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "${MC_TYPE}"
      VERSION: "${MC_VERSION}"
      MEMORY: "${MC_MEMORY}"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    volumes:
      - ./data:/data
    stop_grace_period: 120s
    restart: unless-stopped

  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "${BACKUP_INTERVAL}"
      INITIAL_DELAY: "2m"
      RCON_HOST: "mc"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      BACKUP_METHOD: "rclone"
      RCLONE_REMOTE: "gcs"
      RCLONE_DEST_DIR: "${BACKUP_DEST_DIR}"
      PRUNE_BACKUPS_DAYS: "${PRUNE_BACKUPS_DAYS}"
      RCLONE_CONFIG_GCS_TYPE: "google cloud storage"
      RCLONE_CONFIG_GCS_ENV_AUTH: "true"
      RCLONE_CONFIG_GCS_PROJECT_NUMBER: "${GCP_PROJECT}"
      RCLONE_CONFIG_GCS_BUCKET_POLICY_ONLY: "true"
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
